const http = require("http");
const fs = require("fs");
const path = require("path");
const root = __dirname;
const dropboxRoot = path.resolve(root, "..", "..", "..");
const dataPath = path.join(dropboxRoot, "drawing_takeoff_data", "latest.json");
const port = Number(process.argv[2] || process.env.PORT || 8777);
const mime = {".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json; charset=utf-8",".png":"image/png",".mjs":"text/javascript; charset=utf-8",".pdf":"application/pdf"};
function inside(parent,target){const r=path.relative(parent,target);return r===""||(!r.startsWith("..")&&!path.isAbsolute(r));}
function validate(text){const d=JSON.parse(text);if(d.format!=="drawing-takeoff-project-book-v1"||!Array.isArray(d.book?.projects)||!d.book.projects.length)throw new Error("invalid project data");}
async function body(req){const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>100*1024*1024)throw new Error("data too large");chunks.push(c);}return Buffer.concat(chunks).toString("utf8");}
function send(res,status,content,type="text/plain; charset=utf-8"){res.writeHead(status,{"Content-Type":type,"Cache-Control":"no-store"});res.end(content);}
async function save(req,res){try{const content=await body(req);validate(content);if(!inside(dropboxRoot,dataPath))throw new Error("invalid path");await fs.promises.mkdir(path.dirname(dataPath),{recursive:true});try{const old=await fs.promises.readFile(dataPath,"utf8");validate(old);await fs.promises.writeFile(dataPath+".last-good",old,"utf8");}catch{}const temp=dataPath+".tmp-"+process.pid;await fs.promises.writeFile(temp,content,"utf8");validate(await fs.promises.readFile(temp,"utf8"));await fs.promises.rename(temp,dataPath).catch(async()=>{await fs.promises.copyFile(temp,dataPath);await fs.promises.unlink(temp).catch(()=>{});});send(res,200,JSON.stringify({ok:true,savedAt:new Date().toISOString()}),"application/json; charset=utf-8");}catch(e){send(res,500,"save failed: "+e.message);}}
async function serve(req,res){const url=new URL(req.url,"http://127.0.0.1");const file=path.resolve(root,decodeURIComponent(url.pathname)==="/"?"index.html":decodeURIComponent(url.pathname).replace(/^\/+/, ""));if(!inside(root,file))return send(res,403,"forbidden");try{const stat=await fs.promises.stat(file);if(!stat.isFile())return send(res,404,"not found");res.writeHead(200,{"Content-Type":mime[path.extname(file).toLowerCase()]||"application/octet-stream","Cache-Control":"no-store"});fs.createReadStream(file).pipe(res);}catch{send(res,404,"not found");}}
http.createServer(async(req,res)=>{if(req.method==="GET"&&req.url==="/api/health")return send(res,200,'{"ok":true}',"application/json; charset=utf-8");if(req.method==="POST"&&req.url==="/api/save-data")return save(req,res);if(req.method==="GET"&&req.url==="/api/latest-data"){try{const content=await fs.promises.readFile(dataPath,"utf8");validate(content);return send(res,200,content,"application/json; charset=utf-8");}catch(e){return send(res,404,"load failed: "+e.message);}}if(req.method==="GET"||req.method==="HEAD")return serve(req,res);send(res,405,"method not allowed");}).listen(port,"127.0.0.1",()=>console.log("drawing takeoff app: http://127.0.0.1:"+port+"/"));
